### ISSUE TITLE
Error on run - fails after a semi-arbitrary number of blocks

### ISSUE THREAD

**Issue by israelmirsky** [Aldaschwede/EtherDeltaTrades#1]
Traceback (most recent call last):
  File "trades.py", line 218, in <module>
    getTrades(args.fromBlock,args.toBlock, args.ETHAdress)
  File "trades.py", line 208, in getTrades
    getTradesInBlockRange(call, file,ethereumAdress[2:])
  File "trades.py", line 188, in getTradesInBlockRange
    f.write(e)
TypeError: expected a character buffer object

**Comment by Aldaschwede** [comment]
Could you give me your parameters you provided to start the script? So maybe I can reconstruct the error
